name: Helm Release

on:
  push:
    branches: [ "main" ]
    paths:
      - "infra/helm/**"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: helm-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Helm Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.15.4

      - name: Helm lint
        run: |
          helm lint infra/helm/winmem

  publish:
    name: Publish Helm Chart
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.15.4

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install chart releaser
        run: |
          curl -sSL https://github.com/helm/chart-releaser/releases/download/v1.6.0/chart-releaser_1.6.0_linux_amd64.tar.gz | tar -xz
          sudo mv cr /usr/local/bin/cr
          cr version

      - name: Package charts
        run: |
          mkdir -p .cr-release-packages
          cr package infra/helm/winmem --package-path .cr-release-packages

      - name: Upload charts to GitHub Releases
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cr upload --owner ${{ github.repository_owner }} --git-repo ${{ github.event.repository.name }} --packages-with-index --package-path .cr-release-packages

      - name: Update index.yaml on gh-pages
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cr index --owner ${{ github.repository_owner }} --git-repo ${{ github.event.repository.name }} --charts-repo https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }} --push
