name: Security Scan

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

env:
  NODE_VERSION: "20"
  PNPM_VERSION: "9"

jobs:
  npm-audit:
    name: Dependency Audit (pnpm)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: pnpm audit
        run: |
          pnpm audit --audit-level=high || true

  trivy-repo:
    name: Trivy (filesystem)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trivy filesystem scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: "fs"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
          format: "sarif"
          output: "trivy-fs.sarif"

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-fs.sarif

  trivy-images:
    name: Trivy (container images)
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    strategy:
      fail-fast: false
      matrix:
        image:
          - infra/docker/Dockerfile.api
          - infra/docker/Dockerfile.worker
          - infra/docker/Dockerfile.web
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image (local)
        run: |
          docker build -f ${{ matrix.image }} -t winmem-scan:latest .

      - name: Trivy image scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: "winmem-scan:latest"
          format: "sarif"
          output: "trivy-image.sarif"
          severity: "CRITICAL,HIGH"
          ignore-unfixed: true

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-image.sarif
